package bigsword.eleave.db.persistence;

import bigsword.eleave.db.object.model.BsLeaveManagement;
import bigsword.eleave.db.object.model.BsLeaveManagementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsLeaveManagementMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_management
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int countByExample(BsLeaveManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_management
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByExample(BsLeaveManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_management
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_management
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insert(BsLeaveManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_management
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insertSelective(BsLeaveManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_management
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	List<BsLeaveManagement> selectByExample(BsLeaveManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_management
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	BsLeaveManagement selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_management
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExampleSelective(@Param("record") BsLeaveManagement record,
			@Param("example") BsLeaveManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_management
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExample(@Param("record") BsLeaveManagement record, @Param("example") BsLeaveManagementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_management
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKeySelective(BsLeaveManagement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_management
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKey(BsLeaveManagement record);
}