package bigsword.eleave.db.persistence;

import bigsword.eleave.db.object.model.BsLeaveRequest;
import bigsword.eleave.db.object.model.BsLeaveRequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsLeaveRequestMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int countByExample(BsLeaveRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByExample(BsLeaveRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByPrimaryKey(String requestId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insert(BsLeaveRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insertSelective(BsLeaveRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	List<BsLeaveRequest> selectByExample(BsLeaveRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	BsLeaveRequest selectByPrimaryKey(String requestId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExampleSelective(@Param("record") BsLeaveRequest record,
			@Param("example") BsLeaveRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExample(@Param("record") BsLeaveRequest record, @Param("example") BsLeaveRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKeySelective(BsLeaveRequest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKey(BsLeaveRequest record);
}