package bigsword.eleave.db.persistence;

import bigsword.eleave.db.object.model.BsUserAttribute;
import bigsword.eleave.db.object.model.BsUserAttributeExample;
import bigsword.eleave.db.object.model.BsUserAttributeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsUserAttributeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user_attribute
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int countByExample(BsUserAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user_attribute
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByExample(BsUserAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user_attribute
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user_attribute
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insert(BsUserAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user_attribute
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insertSelective(BsUserAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user_attribute
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	List<BsUserAttribute> selectByExample(BsUserAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user_attribute
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	BsUserAttribute selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user_attribute
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExampleSelective(@Param("record") BsUserAttribute record,
			@Param("example") BsUserAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user_attribute
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExample(@Param("record") BsUserAttribute record, @Param("example") BsUserAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user_attribute
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKeySelective(BsUserAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user_attribute
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKey(BsUserAttribute record);
}