package bigsword.eleave.db.persistence;

import bigsword.eleave.db.object.model.BsUser;
import bigsword.eleave.db.object.model.BsUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int countByExample(BsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByExample(BsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insert(BsUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insertSelective(BsUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	List<BsUser> selectByExample(BsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	BsUser selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExampleSelective(@Param("record") BsUser record, @Param("example") BsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExample(@Param("record") BsUser record, @Param("example") BsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKeySelective(BsUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_user
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKey(BsUser record);
}