package bigsword.eleave.db.persistence;

import bigsword.eleave.db.object.model.CategoryLookup;
import bigsword.eleave.db.object.model.CategoryLookupExample;
import bigsword.eleave.db.object.model.CategoryLookupKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryLookupMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_lookup
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int countByExample(CategoryLookupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_lookup
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByExample(CategoryLookupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_lookup
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_lookup
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insert(CategoryLookup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_lookup
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insertSelective(CategoryLookup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_lookup
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	List<CategoryLookup> selectByExample(CategoryLookupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_lookup
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	CategoryLookup selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_lookup
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExampleSelective(@Param("record") CategoryLookup record,
			@Param("example") CategoryLookupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_lookup
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExample(@Param("record") CategoryLookup record, @Param("example") CategoryLookupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_lookup
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKeySelective(CategoryLookup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table category_lookup
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKey(CategoryLookup record);
}