package bigsword.eleave.db.persistence;

import bigsword.eleave.db.object.model.Grade;
import bigsword.eleave.db.object.model.GradeExample;
import bigsword.eleave.db.object.model.GradeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GradeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int countByExample(GradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByExample(GradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insert(Grade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insertSelective(Grade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	List<Grade> selectByExample(GradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	Grade selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Grade record, @Param("example") GradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExample(@Param("record") Grade record, @Param("example") GradeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKeySelective(Grade record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table grade
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKey(Grade record);
}