package bigsword.eleave.db.persistence;

import bigsword.eleave.db.object.model.SpecialDate;
import bigsword.eleave.db.object.model.SpecialDateExample;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecialDateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table special_date
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int countByExample(SpecialDateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table special_date
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByExample(SpecialDateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table special_date
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int deleteByPrimaryKey(Date spDate);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table special_date
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insert(SpecialDate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table special_date
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int insertSelective(SpecialDate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table special_date
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	List<SpecialDate> selectByExample(SpecialDateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table special_date
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	SpecialDate selectByPrimaryKey(Date spDate);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table special_date
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExampleSelective(@Param("record") SpecialDate record, @Param("example") SpecialDateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table special_date
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByExample(@Param("record") SpecialDate record, @Param("example") SpecialDateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table special_date
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKeySelective(SpecialDate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table special_date
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	int updateByPrimaryKey(SpecialDate record);
}