package bigsword.eleave.db.object.model;

import java.util.Date;
import java.math.BigDecimal;

public class BsLeaveManagement {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_management.ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_management.USER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_management.YEAR_OF
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String yearOf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_management.LEAVE_TYPE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String leaveType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_management.LEAVE_E
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private BigDecimal leaveE;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_management.LEAVE_O
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private BigDecimal leaveO;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_management.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_management.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_management.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_management.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_management.ID
	 * @return  the value of bs_leave_management.ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_management.ID
	 * @param id  the value for bs_leave_management.ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_management.USER_ID
	 * @return  the value of bs_leave_management.USER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_management.USER_ID
	 * @param userId  the value for bs_leave_management.USER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_management.YEAR_OF
	 * @return  the value of bs_leave_management.YEAR_OF
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getYearOf() {
		return yearOf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_management.YEAR_OF
	 * @param yearOf  the value for bs_leave_management.YEAR_OF
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setYearOf(String yearOf) {
		this.yearOf = yearOf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_management.LEAVE_TYPE
	 * @return  the value of bs_leave_management.LEAVE_TYPE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getLeaveType() {
		return leaveType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_management.LEAVE_TYPE
	 * @param leaveType  the value for bs_leave_management.LEAVE_TYPE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setLeaveType(String leaveType) {
		this.leaveType = leaveType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_management.LEAVE_E
	 * @return  the value of bs_leave_management.LEAVE_E
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public BigDecimal getLeaveE() {
		return leaveE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_management.LEAVE_E
	 * @param leaveE  the value for bs_leave_management.LEAVE_E
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setLeaveE(BigDecimal leaveE) {
		this.leaveE = leaveE;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_management.LEAVE_O
	 * @return  the value of bs_leave_management.LEAVE_O
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public BigDecimal getLeaveO() {
		return leaveO;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_management.LEAVE_O
	 * @param leaveO  the value for bs_leave_management.LEAVE_O
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setLeaveO(BigDecimal leaveO) {
		this.leaveO = leaveO;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_management.CREATE_DATE
	 * @return  the value of bs_leave_management.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_management.CREATE_DATE
	 * @param createDate  the value for bs_leave_management.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_management.CREATE_BY
	 * @return  the value of bs_leave_management.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_management.CREATE_BY
	 * @param createBy  the value for bs_leave_management.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_management.UPDATE_DATE
	 * @return  the value of bs_leave_management.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_management.UPDATE_DATE
	 * @param updateDate  the value for bs_leave_management.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_management.UPDATE_BY
	 * @return  the value of bs_leave_management.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_management.UPDATE_BY
	 * @param updateBy  the value for bs_leave_management.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
}