package bigsword.eleave.db.object.model;

import java.util.Date;
import java.math.BigDecimal;

public class BsLeaveRequest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.REQUEST_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String requestId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.USER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.LEAVE_TYPE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String leaveType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.START_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.TO_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date toDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.LEAVE_days
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private BigDecimal leaveDays;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.REQUEST_STATUS
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String requestStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.REASON
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.COMMENT
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.task_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String taskId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_leave_request.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.REQUEST_ID
	 * @return  the value of bs_leave_request.REQUEST_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getRequestId() {
		return requestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.REQUEST_ID
	 * @param requestId  the value for bs_leave_request.REQUEST_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.USER_ID
	 * @return  the value of bs_leave_request.USER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.USER_ID
	 * @param userId  the value for bs_leave_request.USER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.LEAVE_TYPE
	 * @return  the value of bs_leave_request.LEAVE_TYPE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getLeaveType() {
		return leaveType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.LEAVE_TYPE
	 * @param leaveType  the value for bs_leave_request.LEAVE_TYPE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setLeaveType(String leaveType) {
		this.leaveType = leaveType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.START_DATE
	 * @return  the value of bs_leave_request.START_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.START_DATE
	 * @param startDate  the value for bs_leave_request.START_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.TO_DATE
	 * @return  the value of bs_leave_request.TO_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getToDate() {
		return toDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.TO_DATE
	 * @param toDate  the value for bs_leave_request.TO_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.LEAVE_days
	 * @return  the value of bs_leave_request.LEAVE_days
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public BigDecimal getLeaveDays() {
		return leaveDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.LEAVE_days
	 * @param leaveDays  the value for bs_leave_request.LEAVE_days
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setLeaveDays(BigDecimal leaveDays) {
		this.leaveDays = leaveDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.REQUEST_STATUS
	 * @return  the value of bs_leave_request.REQUEST_STATUS
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getRequestStatus() {
		return requestStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.REQUEST_STATUS
	 * @param requestStatus  the value for bs_leave_request.REQUEST_STATUS
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setRequestStatus(String requestStatus) {
		this.requestStatus = requestStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.REASON
	 * @return  the value of bs_leave_request.REASON
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.REASON
	 * @param reason  the value for bs_leave_request.REASON
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.COMMENT
	 * @return  the value of bs_leave_request.COMMENT
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.COMMENT
	 * @param comment  the value for bs_leave_request.COMMENT
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.task_ID
	 * @return  the value of bs_leave_request.task_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getTaskId() {
		return taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.task_ID
	 * @param taskId  the value for bs_leave_request.task_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.CREATE_DATE
	 * @return  the value of bs_leave_request.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.CREATE_DATE
	 * @param createDate  the value for bs_leave_request.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.CREATE_BY
	 * @return  the value of bs_leave_request.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.CREATE_BY
	 * @param createBy  the value for bs_leave_request.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.UPDATE_DATE
	 * @return  the value of bs_leave_request.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.UPDATE_DATE
	 * @param updateDate  the value for bs_leave_request.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_leave_request.UPDATE_BY
	 * @return  the value of bs_leave_request.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_leave_request.UPDATE_BY
	 * @param updateBy  the value for bs_leave_request.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
}