package bigsword.eleave.db.object.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.math.BigDecimal;

public class BsLeaveRequestExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public BsLeaveRequestExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andRequestIdIsNull() {
			addCriterion("REQUEST_ID is null");
			return (Criteria) this;
		}

		public Criteria andRequestIdIsNotNull() {
			addCriterion("REQUEST_ID is not null");
			return (Criteria) this;
		}

		public Criteria andRequestIdEqualTo(String value) {
			addCriterion("REQUEST_ID =", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotEqualTo(String value) {
			addCriterion("REQUEST_ID <>", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdGreaterThan(String value) {
			addCriterion("REQUEST_ID >", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdGreaterThanOrEqualTo(String value) {
			addCriterion("REQUEST_ID >=", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdLessThan(String value) {
			addCriterion("REQUEST_ID <", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdLessThanOrEqualTo(String value) {
			addCriterion("REQUEST_ID <=", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdLike(String value) {
			addCriterion("REQUEST_ID like", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotLike(String value) {
			addCriterion("REQUEST_ID not like", value, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdIn(List<String> values) {
			addCriterion("REQUEST_ID in", values, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotIn(List<String> values) {
			addCriterion("REQUEST_ID not in", values, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdBetween(String value1, String value2) {
			addCriterion("REQUEST_ID between", value1, value2, "requestId");
			return (Criteria) this;
		}

		public Criteria andRequestIdNotBetween(String value1, String value2) {
			addCriterion("REQUEST_ID not between", value1, value2, "requestId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(String value) {
			addCriterion("USER_ID =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(String value) {
			addCriterion("USER_ID <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(String value) {
			addCriterion("USER_ID >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(String value) {
			addCriterion("USER_ID >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(String value) {
			addCriterion("USER_ID <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(String value) {
			addCriterion("USER_ID <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLike(String value) {
			addCriterion("USER_ID like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotLike(String value) {
			addCriterion("USER_ID not like", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<String> values) {
			addCriterion("USER_ID in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<String> values) {
			addCriterion("USER_ID not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(String value1, String value2) {
			addCriterion("USER_ID between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(String value1, String value2) {
			addCriterion("USER_ID not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeIsNull() {
			addCriterion("LEAVE_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeIsNotNull() {
			addCriterion("LEAVE_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeEqualTo(String value) {
			addCriterion("LEAVE_TYPE =", value, "leaveType");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeNotEqualTo(String value) {
			addCriterion("LEAVE_TYPE <>", value, "leaveType");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeGreaterThan(String value) {
			addCriterion("LEAVE_TYPE >", value, "leaveType");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeGreaterThanOrEqualTo(String value) {
			addCriterion("LEAVE_TYPE >=", value, "leaveType");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeLessThan(String value) {
			addCriterion("LEAVE_TYPE <", value, "leaveType");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeLessThanOrEqualTo(String value) {
			addCriterion("LEAVE_TYPE <=", value, "leaveType");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeLike(String value) {
			addCriterion("LEAVE_TYPE like", value, "leaveType");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeNotLike(String value) {
			addCriterion("LEAVE_TYPE not like", value, "leaveType");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeIn(List<String> values) {
			addCriterion("LEAVE_TYPE in", values, "leaveType");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeNotIn(List<String> values) {
			addCriterion("LEAVE_TYPE not in", values, "leaveType");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeBetween(String value1, String value2) {
			addCriterion("LEAVE_TYPE between", value1, value2, "leaveType");
			return (Criteria) this;
		}

		public Criteria andLeaveTypeNotBetween(String value1, String value2) {
			addCriterion("LEAVE_TYPE not between", value1, value2, "leaveType");
			return (Criteria) this;
		}

		public Criteria andStartDateIsNull() {
			addCriterion("START_DATE is null");
			return (Criteria) this;
		}

		public Criteria andStartDateIsNotNull() {
			addCriterion("START_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andStartDateEqualTo(Date value) {
			addCriterionForJDBCDate("START_DATE =", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("START_DATE <>", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateGreaterThan(Date value) {
			addCriterionForJDBCDate("START_DATE >", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("START_DATE >=", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateLessThan(Date value) {
			addCriterionForJDBCDate("START_DATE <", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("START_DATE <=", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateIn(List<Date> values) {
			addCriterionForJDBCDate("START_DATE in", values, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("START_DATE not in", values, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("START_DATE between", value1, value2, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("START_DATE not between", value1, value2, "startDate");
			return (Criteria) this;
		}

		public Criteria andToDateIsNull() {
			addCriterion("TO_DATE is null");
			return (Criteria) this;
		}

		public Criteria andToDateIsNotNull() {
			addCriterion("TO_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andToDateEqualTo(Date value) {
			addCriterionForJDBCDate("TO_DATE =", value, "toDate");
			return (Criteria) this;
		}

		public Criteria andToDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("TO_DATE <>", value, "toDate");
			return (Criteria) this;
		}

		public Criteria andToDateGreaterThan(Date value) {
			addCriterionForJDBCDate("TO_DATE >", value, "toDate");
			return (Criteria) this;
		}

		public Criteria andToDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("TO_DATE >=", value, "toDate");
			return (Criteria) this;
		}

		public Criteria andToDateLessThan(Date value) {
			addCriterionForJDBCDate("TO_DATE <", value, "toDate");
			return (Criteria) this;
		}

		public Criteria andToDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("TO_DATE <=", value, "toDate");
			return (Criteria) this;
		}

		public Criteria andToDateIn(List<Date> values) {
			addCriterionForJDBCDate("TO_DATE in", values, "toDate");
			return (Criteria) this;
		}

		public Criteria andToDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("TO_DATE not in", values, "toDate");
			return (Criteria) this;
		}

		public Criteria andToDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("TO_DATE between", value1, value2, "toDate");
			return (Criteria) this;
		}

		public Criteria andToDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("TO_DATE not between", value1, value2, "toDate");
			return (Criteria) this;
		}

		public Criteria andLeaveDaysIsNull() {
			addCriterion("LEAVE_days is null");
			return (Criteria) this;
		}

		public Criteria andLeaveDaysIsNotNull() {
			addCriterion("LEAVE_days is not null");
			return (Criteria) this;
		}

		public Criteria andLeaveDaysEqualTo(BigDecimal value) {
			addCriterion("LEAVE_days =", value, "leaveDays");
			return (Criteria) this;
		}

		public Criteria andLeaveDaysNotEqualTo(BigDecimal value) {
			addCriterion("LEAVE_days <>", value, "leaveDays");
			return (Criteria) this;
		}

		public Criteria andLeaveDaysGreaterThan(BigDecimal value) {
			addCriterion("LEAVE_days >", value, "leaveDays");
			return (Criteria) this;
		}

		public Criteria andLeaveDaysGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("LEAVE_days >=", value, "leaveDays");
			return (Criteria) this;
		}

		public Criteria andLeaveDaysLessThan(BigDecimal value) {
			addCriterion("LEAVE_days <", value, "leaveDays");
			return (Criteria) this;
		}

		public Criteria andLeaveDaysLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LEAVE_days <=", value, "leaveDays");
			return (Criteria) this;
		}

		public Criteria andLeaveDaysIn(List<BigDecimal> values) {
			addCriterion("LEAVE_days in", values, "leaveDays");
			return (Criteria) this;
		}

		public Criteria andLeaveDaysNotIn(List<BigDecimal> values) {
			addCriterion("LEAVE_days not in", values, "leaveDays");
			return (Criteria) this;
		}

		public Criteria andLeaveDaysBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("LEAVE_days between", value1, value2, "leaveDays");
			return (Criteria) this;
		}

		public Criteria andLeaveDaysNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("LEAVE_days not between", value1, value2, "leaveDays");
			return (Criteria) this;
		}

		public Criteria andRequestStatusIsNull() {
			addCriterion("REQUEST_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andRequestStatusIsNotNull() {
			addCriterion("REQUEST_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andRequestStatusEqualTo(String value) {
			addCriterion("REQUEST_STATUS =", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusNotEqualTo(String value) {
			addCriterion("REQUEST_STATUS <>", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusGreaterThan(String value) {
			addCriterion("REQUEST_STATUS >", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusGreaterThanOrEqualTo(String value) {
			addCriterion("REQUEST_STATUS >=", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusLessThan(String value) {
			addCriterion("REQUEST_STATUS <", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusLessThanOrEqualTo(String value) {
			addCriterion("REQUEST_STATUS <=", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusLike(String value) {
			addCriterion("REQUEST_STATUS like", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusNotLike(String value) {
			addCriterion("REQUEST_STATUS not like", value, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusIn(List<String> values) {
			addCriterion("REQUEST_STATUS in", values, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusNotIn(List<String> values) {
			addCriterion("REQUEST_STATUS not in", values, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusBetween(String value1, String value2) {
			addCriterion("REQUEST_STATUS between", value1, value2, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andRequestStatusNotBetween(String value1, String value2) {
			addCriterion("REQUEST_STATUS not between", value1, value2, "requestStatus");
			return (Criteria) this;
		}

		public Criteria andReasonIsNull() {
			addCriterion("REASON is null");
			return (Criteria) this;
		}

		public Criteria andReasonIsNotNull() {
			addCriterion("REASON is not null");
			return (Criteria) this;
		}

		public Criteria andReasonEqualTo(String value) {
			addCriterion("REASON =", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotEqualTo(String value) {
			addCriterion("REASON <>", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonGreaterThan(String value) {
			addCriterion("REASON >", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonGreaterThanOrEqualTo(String value) {
			addCriterion("REASON >=", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLessThan(String value) {
			addCriterion("REASON <", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLessThanOrEqualTo(String value) {
			addCriterion("REASON <=", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLike(String value) {
			addCriterion("REASON like", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotLike(String value) {
			addCriterion("REASON not like", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonIn(List<String> values) {
			addCriterion("REASON in", values, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotIn(List<String> values) {
			addCriterion("REASON not in", values, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonBetween(String value1, String value2) {
			addCriterion("REASON between", value1, value2, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotBetween(String value1, String value2) {
			addCriterion("REASON not between", value1, value2, "reason");
			return (Criteria) this;
		}

		public Criteria andCommentIsNull() {
			addCriterion("COMMENT is null");
			return (Criteria) this;
		}

		public Criteria andCommentIsNotNull() {
			addCriterion("COMMENT is not null");
			return (Criteria) this;
		}

		public Criteria andCommentEqualTo(String value) {
			addCriterion("COMMENT =", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotEqualTo(String value) {
			addCriterion("COMMENT <>", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThan(String value) {
			addCriterion("COMMENT >", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentGreaterThanOrEqualTo(String value) {
			addCriterion("COMMENT >=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThan(String value) {
			addCriterion("COMMENT <", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLessThanOrEqualTo(String value) {
			addCriterion("COMMENT <=", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentLike(String value) {
			addCriterion("COMMENT like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotLike(String value) {
			addCriterion("COMMENT not like", value, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentIn(List<String> values) {
			addCriterion("COMMENT in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotIn(List<String> values) {
			addCriterion("COMMENT not in", values, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentBetween(String value1, String value2) {
			addCriterion("COMMENT between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andCommentNotBetween(String value1, String value2) {
			addCriterion("COMMENT not between", value1, value2, "comment");
			return (Criteria) this;
		}

		public Criteria andTaskIdIsNull() {
			addCriterion("task_ID is null");
			return (Criteria) this;
		}

		public Criteria andTaskIdIsNotNull() {
			addCriterion("task_ID is not null");
			return (Criteria) this;
		}

		public Criteria andTaskIdEqualTo(String value) {
			addCriterion("task_ID =", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotEqualTo(String value) {
			addCriterion("task_ID <>", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThan(String value) {
			addCriterion("task_ID >", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
			addCriterion("task_ID >=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThan(String value) {
			addCriterion("task_ID <", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThanOrEqualTo(String value) {
			addCriterion("task_ID <=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLike(String value) {
			addCriterion("task_ID like", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotLike(String value) {
			addCriterion("task_ID not like", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdIn(List<String> values) {
			addCriterion("task_ID in", values, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotIn(List<String> values) {
			addCriterion("task_ID not in", values, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdBetween(String value1, String value2) {
			addCriterion("task_ID between", value1, value2, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotBetween(String value1, String value2) {
			addCriterion("task_ID not between", value1, value2, "taskId");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("CREATE_DATE =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("CREATE_DATE <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("CREATE_DATE >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("CREATE_DATE <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("CREATE_DATE in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("CREATE_DATE not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNull() {
			addCriterion("CREATE_BY is null");
			return (Criteria) this;
		}

		public Criteria andCreateByIsNotNull() {
			addCriterion("CREATE_BY is not null");
			return (Criteria) this;
		}

		public Criteria andCreateByEqualTo(String value) {
			addCriterion("CREATE_BY =", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotEqualTo(String value) {
			addCriterion("CREATE_BY <>", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThan(String value) {
			addCriterion("CREATE_BY >", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_BY >=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThan(String value) {
			addCriterion("CREATE_BY <", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLessThanOrEqualTo(String value) {
			addCriterion("CREATE_BY <=", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByLike(String value) {
			addCriterion("CREATE_BY like", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotLike(String value) {
			addCriterion("CREATE_BY not like", value, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByIn(List<String> values) {
			addCriterion("CREATE_BY in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotIn(List<String> values) {
			addCriterion("CREATE_BY not in", values, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByBetween(String value1, String value2) {
			addCriterion("CREATE_BY between", value1, value2, "createBy");
			return (Criteria) this;
		}

		public Criteria andCreateByNotBetween(String value1, String value2) {
			addCriterion("CREATE_BY not between", value1, value2, "createBy");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("UPDATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("UPDATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("UPDATE_DATE =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("UPDATE_DATE <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("UPDATE_DATE >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("UPDATE_DATE <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_DATE <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("UPDATE_DATE in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("UPDATE_DATE not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateByIsNull() {
			addCriterion("UPDATE_BY is null");
			return (Criteria) this;
		}

		public Criteria andUpdateByIsNotNull() {
			addCriterion("UPDATE_BY is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateByEqualTo(String value) {
			addCriterion("UPDATE_BY =", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotEqualTo(String value) {
			addCriterion("UPDATE_BY <>", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByGreaterThan(String value) {
			addCriterion("UPDATE_BY >", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_BY >=", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByLessThan(String value) {
			addCriterion("UPDATE_BY <", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_BY <=", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByLike(String value) {
			addCriterion("UPDATE_BY like", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotLike(String value) {
			addCriterion("UPDATE_BY not like", value, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByIn(List<String> values) {
			addCriterion("UPDATE_BY in", values, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotIn(List<String> values) {
			addCriterion("UPDATE_BY not in", values, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByBetween(String value1, String value2) {
			addCriterion("UPDATE_BY between", value1, value2, "updateBy");
			return (Criteria) this;
		}

		public Criteria andUpdateByNotBetween(String value1, String value2) {
			addCriterion("UPDATE_BY not between", value1, value2, "updateBy");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bs_leave_request
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bs_leave_request
     *
     * @mbggenerated do_not_delete_during_merge Sun Feb 28 14:52:34 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}