package bigsword.eleave.db.object.model;

import java.util.Date;

public class BsUserAttribute {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user_attribute.ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user_attribute.USER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user_attribute.NAME
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user_attribute.VALUE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user_attribute.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user_attribute.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user_attribute.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user_attribute.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user_attribute.ID
	 * @return  the value of bs_user_attribute.ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user_attribute.ID
	 * @param id  the value for bs_user_attribute.ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user_attribute.USER_ID
	 * @return  the value of bs_user_attribute.USER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user_attribute.USER_ID
	 * @param userId  the value for bs_user_attribute.USER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user_attribute.NAME
	 * @return  the value of bs_user_attribute.NAME
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user_attribute.NAME
	 * @param name  the value for bs_user_attribute.NAME
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user_attribute.VALUE
	 * @return  the value of bs_user_attribute.VALUE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user_attribute.VALUE
	 * @param value  the value for bs_user_attribute.VALUE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user_attribute.CREATE_DATE
	 * @return  the value of bs_user_attribute.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user_attribute.CREATE_DATE
	 * @param createDate  the value for bs_user_attribute.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user_attribute.CREATE_BY
	 * @return  the value of bs_user_attribute.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user_attribute.CREATE_BY
	 * @param createBy  the value for bs_user_attribute.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user_attribute.UPDATE_DATE
	 * @return  the value of bs_user_attribute.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user_attribute.UPDATE_DATE
	 * @param updateDate  the value for bs_user_attribute.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user_attribute.UPDATE_BY
	 * @return  the value of bs_user_attribute.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user_attribute.UPDATE_BY
	 * @param updateBy  the value for bs_user_attribute.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
}