package bigsword.eleave.db.object.model;

import java.util.Date;

public class BsUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.USER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.NAME
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.GENDER
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.EMAIL
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.USER_TYPE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.STATUS
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.JOIN_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date joinDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.RESIGN_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date resignDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.MANAGER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String managerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.USER_ID
	 * @return  the value of bs_user.USER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.USER_ID
	 * @param userId  the value for bs_user.USER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.NAME
	 * @return  the value of bs_user.NAME
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.NAME
	 * @param name  the value for bs_user.NAME
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.GENDER
	 * @return  the value of bs_user.GENDER
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.GENDER
	 * @param gender  the value for bs_user.GENDER
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.EMAIL
	 * @return  the value of bs_user.EMAIL
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.EMAIL
	 * @param email  the value for bs_user.EMAIL
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.USER_TYPE
	 * @return  the value of bs_user.USER_TYPE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.USER_TYPE
	 * @param userType  the value for bs_user.USER_TYPE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUserType(String userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.STATUS
	 * @return  the value of bs_user.STATUS
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.STATUS
	 * @param status  the value for bs_user.STATUS
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.JOIN_DATE
	 * @return  the value of bs_user.JOIN_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getJoinDate() {
		return joinDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.JOIN_DATE
	 * @param joinDate  the value for bs_user.JOIN_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.RESIGN_DATE
	 * @return  the value of bs_user.RESIGN_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getResignDate() {
		return resignDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.RESIGN_DATE
	 * @param resignDate  the value for bs_user.RESIGN_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setResignDate(Date resignDate) {
		this.resignDate = resignDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.MANAGER_ID
	 * @return  the value of bs_user.MANAGER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.MANAGER_ID
	 * @param managerId  the value for bs_user.MANAGER_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setManagerId(String managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.CREATE_DATE
	 * @return  the value of bs_user.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.CREATE_DATE
	 * @param createDate  the value for bs_user.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.CREATE_BY
	 * @return  the value of bs_user.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.CREATE_BY
	 * @param createBy  the value for bs_user.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.UPDATE_DATE
	 * @return  the value of bs_user.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.UPDATE_DATE
	 * @param updateDate  the value for bs_user.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user.UPDATE_BY
	 * @return  the value of bs_user.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user.UPDATE_BY
	 * @param updateBy  the value for bs_user.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
}