package bigsword.eleave.db.object.model;

public class BsUserAttributeKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user_attribute.NAME
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bs_user_attribute.USER_ID
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	private String userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user_attribute.NAME
	 * @return  the value of bs_user_attribute.NAME
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user_attribute.NAME
	 * @param name  the value for bs_user_attribute.NAME
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bs_user_attribute.USER_ID
	 * @return  the value of bs_user_attribute.USER_ID
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bs_user_attribute.USER_ID
	 * @param userId  the value for bs_user_attribute.USER_ID
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}
}