package bigsword.eleave.db.object.model;

public class CategoryLookupKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category_lookup.CATEGORY
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	private String category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category_lookup.NAME
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category_lookup.CATEGORY
	 * @return  the value of category_lookup.CATEGORY
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category_lookup.CATEGORY
	 * @param category  the value for category_lookup.CATEGORY
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category_lookup.NAME
	 * @return  the value of category_lookup.NAME
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category_lookup.NAME
	 * @param name  the value for category_lookup.NAME
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}
}