package bigsword.eleave.db.object.model;

import java.util.Date;

public class Department {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.DEPT_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.DEPT_NAME
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String deptName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.DEPT_HEAD_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String deptHeadId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.DEPT_ID
	 * @return  the value of department.DEPT_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.DEPT_ID
	 * @param deptId  the value for department.DEPT_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.DEPT_NAME
	 * @return  the value of department.DEPT_NAME
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.DEPT_NAME
	 * @param deptName  the value for department.DEPT_NAME
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.DEPT_HEAD_ID
	 * @return  the value of department.DEPT_HEAD_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getDeptHeadId() {
		return deptHeadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.DEPT_HEAD_ID
	 * @param deptHeadId  the value for department.DEPT_HEAD_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setDeptHeadId(String deptHeadId) {
		this.deptHeadId = deptHeadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.CREATE_DATE
	 * @return  the value of department.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.CREATE_DATE
	 * @param createDate  the value for department.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.CREATE_BY
	 * @return  the value of department.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.CREATE_BY
	 * @param createBy  the value for department.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.UPDATE_DATE
	 * @return  the value of department.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.UPDATE_DATE
	 * @param updateDate  the value for department.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.UPDATE_BY
	 * @return  the value of department.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.UPDATE_BY
	 * @param updateBy  the value for department.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
}