package bigsword.eleave.db.object.model;

public class GradeKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.GRADE_ID
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	private String gradeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.WORKING_YEARS
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	private Integer workingYears;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.GRADE_ID
	 * @return  the value of grade.GRADE_ID
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	public String getGradeId() {
		return gradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.GRADE_ID
	 * @param gradeId  the value for grade.GRADE_ID
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	public void setGradeId(String gradeId) {
		this.gradeId = gradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.WORKING_YEARS
	 * @return  the value of grade.WORKING_YEARS
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	public Integer getWorkingYears() {
		return workingYears;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.WORKING_YEARS
	 * @param workingYears  the value for grade.WORKING_YEARS
	 * @mbggenerated  Sun Mar 06 18:31:36 CST 2016
	 */
	public void setWorkingYears(Integer workingYears) {
		this.workingYears = workingYears;
	}
}