package bigsword.eleave.db.object.model;

import java.util.Date;
import java.math.BigDecimal;

public class Grade {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.GRADE_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String gradeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.WORKING_YEARS
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Integer workingYears;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.ANNUAL_LEAVE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private BigDecimal annualLeave;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column grade.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.ID
	 * @return  the value of grade.ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.ID
	 * @param id  the value for grade.ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.GRADE_ID
	 * @return  the value of grade.GRADE_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getGradeId() {
		return gradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.GRADE_ID
	 * @param gradeId  the value for grade.GRADE_ID
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setGradeId(String gradeId) {
		this.gradeId = gradeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.WORKING_YEARS
	 * @return  the value of grade.WORKING_YEARS
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Integer getWorkingYears() {
		return workingYears;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.WORKING_YEARS
	 * @param workingYears  the value for grade.WORKING_YEARS
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setWorkingYears(Integer workingYears) {
		this.workingYears = workingYears;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.ANNUAL_LEAVE
	 * @return  the value of grade.ANNUAL_LEAVE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public BigDecimal getAnnualLeave() {
		return annualLeave;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.ANNUAL_LEAVE
	 * @param annualLeave  the value for grade.ANNUAL_LEAVE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setAnnualLeave(BigDecimal annualLeave) {
		this.annualLeave = annualLeave;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.CREATE_DATE
	 * @return  the value of grade.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.CREATE_DATE
	 * @param createDate  the value for grade.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.CREATE_BY
	 * @return  the value of grade.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.CREATE_BY
	 * @param createBy  the value for grade.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.UPDATE_DATE
	 * @return  the value of grade.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.UPDATE_DATE
	 * @param updateDate  the value for grade.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column grade.UPDATE_BY
	 * @return  the value of grade.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column grade.UPDATE_BY
	 * @param updateBy  the value for grade.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
}