package bigsword.eleave.db.object.model;

import java.util.Date;

public class SpecialDate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column special_date.SP_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date spDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column special_date.DESCRIPTION
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column special_date.TYPE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column special_date.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column special_date.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column special_date.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column special_date.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	private String updateBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column special_date.SP_DATE
	 * @return  the value of special_date.SP_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getSpDate() {
		return spDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column special_date.SP_DATE
	 * @param spDate  the value for special_date.SP_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setSpDate(Date spDate) {
		this.spDate = spDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column special_date.DESCRIPTION
	 * @return  the value of special_date.DESCRIPTION
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column special_date.DESCRIPTION
	 * @param description  the value for special_date.DESCRIPTION
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column special_date.TYPE
	 * @return  the value of special_date.TYPE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column special_date.TYPE
	 * @param type  the value for special_date.TYPE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column special_date.CREATE_DATE
	 * @return  the value of special_date.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column special_date.CREATE_DATE
	 * @param createDate  the value for special_date.CREATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column special_date.CREATE_BY
	 * @return  the value of special_date.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column special_date.CREATE_BY
	 * @param createBy  the value for special_date.CREATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column special_date.UPDATE_DATE
	 * @return  the value of special_date.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column special_date.UPDATE_DATE
	 * @param updateDate  the value for special_date.UPDATE_DATE
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column special_date.UPDATE_BY
	 * @return  the value of special_date.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public String getUpdateBy() {
		return updateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column special_date.UPDATE_BY
	 * @param updateBy  the value for special_date.UPDATE_BY
	 * @mbggenerated  Mon Mar 07 21:25:18 CST 2016
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
}